name: open_fashion
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
#  for localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  localization: ^2.1.0
#  code style
  linter: ^1.27.0
#  logging events
  logging: ^1.1.0
#  work with svg-pictures
  flutter_svg: ^1.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
#  http
  dio: ^4.0.6
#  state management
  flutter_bloc: ^8.1.1
#  di
  get_it: ^7.2.0
  equatable: ^2.0.5
#  firebase
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  firebase_crashlytics: ^3.0.7
#  navigation
  auto_route: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.0.3
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  injectable_generator: ^2.0.1
  auto_route_generator: ^5.0.3

flutter:

  uses-material-design: true
  generate: true

  assets:
    - lib/src/assets/svg/
    - lib/src/assets/png/
  fonts:
    - family: TenorSans-Regular
      fonts:
        - asset: lib/src/assets/font/TenorSans-Regular.ttf
    - family: BodoniModa-BoldItalic
      fonts:
        - asset: lib/src/assets/font/BodoniModa-BoldItalic.ttf
flutter_gen:
  output: lib/src/gen/
  style: camel-case
  integrations:
    flutter_svg: true