name: CI
on:
  pull_request:
jobs:
  lint-test-build-android:
    name: Lint, Test And Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup app_secrets.dart
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}
          SECRETS_FILE_CONTENT_PATH: lib/src/app/secrets/app_secrets.dart
        run: echo -n $SECRETS_FILE_CONTENT | base64 --decode > $SECRETS_FILE_CONTENT_PATH

      - name: Get Dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Lint
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Build Android
        run: scripts/build.sh apk dev --debug

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: [ lint-test-build-android ]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup app_secrets.dart
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}
          SECRETS_FILE_CONTENT_PATH: lib/src/app/secrets/app_secrets.dart
        run: echo -n $SECRETS_FILE_CONTENT | base64 --decode > $SECRETS_FILE_CONTENT_PATH

      - name: Get Dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build

      - name: Build iOS
        run: scripts/build.sh ios dev --debug --no-codesign